### ISSUE TITLE
Deprecated?

### ISSUE THREAD

**Issue by Metaxal** [soegaard/flmatrix#10]
Is this deprecated in favor of https://github.com/soegaard/sci ?

**Comment by soegaard** [comment]
Yes. I'll add a comment in the README.

**Comment by Metaxal** [comment]
The link in the commit is wrong/dead, it should probably be:
https://github.com/soegaard/sci/tree/master/flomat

**Comment by soegaard** [comment]
Thanks - I have fixed the link.
