### ISSUE TITLE
main.rkt?

### ISSUE THREAD

**Issue by Metaxal** [soegaard/flmatrix#5]
What about including a main.rkt that just re-exports flmatrix.rkt?

That would allow for just `(require flmatrix)`  instead of `(require flmatrix/flmatrix)`

**Comment by soegaard** [comment]
Pull requests are welcome :-)

**Comment by Metaxal** [comment]
I wasn't sure you wanted to do that

**Comment by soegaard** [comment]
On second thought - I don't want to do that.

Hopefully someone turns the raw bindings into a more rackety matrix library at some point.
In that case it would be a shame that `(require flmatrix)` imports the raw bindings.
